version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - WEAVECLIENT_HOST=${WEAVECLIENT_HOST}
      - WEAVECLIENT_KEY=${WEAVECLIENT_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE=${HUGGING_FACE}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
  gradio:
    build:
      context: ./gradio
      dockerfile: Dockerfile
    ports:
      - '7860:7860'
    environment:
      - OPENAI_API=${OPENAI_API}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HUGGING_FACE=${HUGGING_FACE}